name: Laravel Docker CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Containers
        run: docker compose build

      - name: Build, Run and Test Laravel App
        run: |
          docker compose up -d
          docker compose exec -T app composer install --no-interaction --prefer-dist --optimize-autoloader
          docker compose exec -T app cp .env.example .env
          docker compose exec -T app php artisan key:generate
          sleep 20
          docker compose ps
          docker compose exec -T app php artisan test
          docker compose down -t 1 --remove-orphans
